### ISSUE TITLE
Update the type definition  abp.d.ts

### ISSUE THREAD

**Issue by julianosaless** [aspnetboilerplate/bower-abp-resources#10]
It is necessary to update the interface, there are methods that have parameters but it was not added in the interface

function:
```
 abp.utils.setCookieValue = function (key, value, expireDate, path, domain) {
} 
```
d.ts

`function setCookieValue(key: string, value: string, expireDate?: Date, path?: string): void;`

**Comment by ismcagdas** [comment]
resolved via https://github.com/aspnetboilerplate/bower-abp-resources/pull/11
