### ISSUE TITLE
Update to ABP v3.7

### ISSUE THREAD

**Issue by acjh** [aspnetboilerplate/bower-abp-resources#14]
...which will include:
- https://github.com/aspnetboilerplate/aspnetboilerplate/pull/3347

**Comment by ismcagdas** [comment]
@acjh should we change this to Update to ABP v3.7 ? SignalR 1.0 is released and Updated in ABP 3.7as you know.

**Comment by acjh** [comment]
@ismcagdas Done!

**Comment by acjh** [comment]
Resolved by 24fcdb6
