### ISSUE TITLE
Wrong abp.clock.now() with UTC time zone.

### ISSUE THREAD

**Issue by dung691** [aspnetboilerplate/bower-abp-resources#15]
Hi,

In source code abp.timing.utcClockProvider now() function
https://github.com/aspnetboilerplate/bower-abp-resources/blob/master/Abp/Framework/scripts/abp.js#L806
I think it should be
var now = function() {
   return toUTC(new Date());
}

I am right?

**Comment by ismcagdas** [comment]
Thanks @dung691 , it is fixed in https://github.com/aspnetboilerplate/bower-abp-resources/issues/15
