### ISSUE TITLE
MessageService typings issue

### ISSUE THREAD

**Issue by jguinto-komaa** [aspnetboilerplate/bower-abp-resources#16]
Typings issue after package update

pacakge version:
![image](https://user-images.githubusercontent.com/40725869/43294411-9aad12c4-912e-11e8-8240-73d1351a6f55.png)

Error expected 1-2  arguments, but got 3
![image](https://user-images.githubusercontent.com/40725869/43294364-6a459e8a-912e-11e8-90d8-09a551d6474d.png)

**Comment by maliming** [comment]
https://github.com/aspnetboilerplate/aspnetboilerplate/issues/3677

**Comment by jguinto-komaa** [comment]
@maliming Thank you for the response. i know this is a stupid question, but how can i get the update?

**Comment by maliming** [comment]
https://github.com/aspnetboilerplate/aspnetboilerplate/blob/688aca6b96e30b46eb508c0292e8fc23d2762396/src/Abp.Web.Resources/Abp/Framework/scripts/abp.d.ts#L292

Before updating, you can paste the repaired code into your local code.
