### ISSUE TITLE
Is there any way to extend  abp.libs.sweetAlert ?

### ISSUE THREAD

**Issue by sachinarora87** [aspnetboilerplate/bower-abp-resources#19]
I want to change the default configuration for sweetAlert but can not find typing for abp.libs.sweetAlert.config. Can we extend the typings?

**Comment by maliming** [comment]
try this: `abp.libs.sweetAlert.config.error.icon = "xxx"`

**Comment by sachinarora87** [comment]
I tried this already it works with and typescript compilation error because the libs is not defined in the typings. I even tried extending the abp namespace. Still that compliation error comes.

**Comment by maliming** [comment]
You can submit PR to add related Typescript definitions. 🙂

**Comment by sachinarora87** [comment]
Closing this issue refer aspnetboilerplate issue [3355](https://github.com/aspnetboilerplate/aspnetboilerplate/issues/3355)
