### ISSUE TITLE
Get Request Issue

### ISSUE THREAD

**Issue by Sun13** [aspnetboilerplate/bower-abp-resources#3]
In "abp.utils.buildQueryString" function, if "parameterInfo" is an array, then get a string with some commas,
not a name-value string of array type.
poor English,sorry!

**Comment by hikalkan** [comment]
Hi,

Actually, abp.utils.buildQueryString intended to be used internally by ABP. Can you write some sample code because I could not understand the problem, sorry :)

**Comment by Sun13** [comment]
These are my simplified test codes,just a method for the same input and output with array.
```C#
    //dto
    public class ArrayDto
    {
        public string[] Names { get; set; }
    }

    //interface
    public interface IArrayAppService
    {
        Task<ArrayDto> GetNames(ArrayDto input);
    }

    //appservice
    public class ArrayAppService : ApplicationService, IArrayAppService
    {
        public Task<ArrayDto> GetNames(ArrayDto input)
        {
            return Task.FromResult(input);
        }
    }
```
then,I used this appservice in my js code
```javascript
abp.services.app.array.getNames({
    names:["123","456","789","abc"]
}).done(function(ret){
    console.log(ret);
})
```
at last I got a result like this, the array turned into a string
![image](https://cloud.githubusercontent.com/assets/10394550/20742075/0e77b1ca-b709-11e6-8e61-ad03d249e24b.png)
The result is not correct only when using Get method. if I change it to Post method,the result is right.

**Comment by hikalkan** [comment]
OK, fixed it: https://github.com/aspnetboilerplate/aspnetboilerplate/issues/1603
Will be released in v.1.1.
