### ISSUE TITLE
Has plan migrate to angularjs 1.6 for $http promise?

### ISSUE THREAD

**Issue by hemiaoio** [aspnetboilerplate/bower-abp-resources#9]
abp.ng.js doesn't work perfect for angularjs 1.6.when I use 
```
appService.method().then(function(result){
//because angularjs 1.6 removed $http.success() and $http.error()
//this result not same as angularjs 1.6 earlier.
})
```
>_Forgive my slag English_

**Comment by hikalkan** [comment]
It already works with then. This is a code from our application:

                            editionService.deleteEdition({
                                id: edition.id
                            }).then(function () {
                                vm.getEditions();
                                abp.notify.success(app.localize('SuccessfullyDeleted'));
                            });

**Comment by hemiaoio** [comment]
well ,I upgrade abp.ng.js at local code ，did you have some perfect solution for it?
![image](https://user-images.githubusercontent.com/5441896/31653244-740339c2-b354-11e7-9d0e-02cd1816e38a.png)

**Comment by hikalkan** [comment]
We are writing like that:

                editionService.getEditions({}).then(function (result) {
                    vm.editionGridOptions.data = result.data.items;
                })

**Comment by hemiaoio** [comment]
Well, it seems only that way.
